# config/_default/languages.es.toml

title = "José Luis Pérez"
description = "José Luis Pérez's personal website."
copyright = "@2022, José Luis Pérez"

[author]
name = "José Luis Pérez"
image = "img/author.png"
headline = "Apasionado de la ciberseguridad y la vanlife."
bio ="Ser multipotencial técnico y analítico con ganas conectar, ¿hablamos?"

links = [
  {twitter = "https://twitter.com/jolupers"},
  {linkedin = "https://www.linkedin.com/in/jose-luis-perez-sanchez/"},
  {instagram = "https://www.instagram.com/jolupers/"},
  {telegram = "https://t.me/@jolupers"}
]

